@contentType = application/json

#########################################
### Request: GET /api/Buggy/bad-request
#########################################


GET http://localhost:5000/api/Buggy/bad-request
Content-Type: {{contentType}}


