@contentType = application/json

###############################
### Request: POST /api/Basket
###############################

### Query Parameter: productId
@productId = 0

### Query Parameter: quantity
@quantity = 0


POST http://localhost:5000/api/Basket?productId={{productId}}&quantity={{quantity}}
Content-Type: {{contentType}}


