@contentType = application/json

#########################################
### Request: POST /api/Account/register
#########################################


POST http://localhost:5000/api/Account/register
Content-Type: {{contentType}}

{
  "username": "username",
  "password": "password",
  "email": "email"
}

