name: docker-push and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - '**/.gitignore'
      - '**/.vscode/*'
      - '**/.idea/*'
      - '**/*.log'
      - '**/*.tmp'
      - 'node_modules/**'
      - 'build/**'
      - 'dist/**'
      - 'coverage/**'
      - '.env*'

jobs:
  docker:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:API"
          push: true
          tags: kokorocko/ecommerce:latest

