name: docker-push and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker build and push
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:API"
          push: true
          tags: kokorocko/ecommerce:latest
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      -
        name: Deploy to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{secrets.FLY_ACCESS_TOKEN_DEV}}

